// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYrDISVx7e5OmE2hlrDJQpwxDdbi-2rtk',
    appId: '1:192519439615:web:c21e98b49e7f69d676b8ca',
    messagingSenderId: '192519439615',
    projectId: 'safestreet-6e08d',
    authDomain: 'safestreet-6e08d.firebaseapp.com',
    storageBucket: 'safestreet-6e08d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqw5O5_9H70-_DqOKkb54I-c_N1cv9EQU',
    appId: '1:192519439615:android:ef1f45511460c5df76b8ca',
    messagingSenderId: '192519439615',
    projectId: 'safestreet-6e08d',
    storageBucket: 'safestreet-6e08d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbTjEHwE_gF985otrlxqx48KS8H5dT_N8',
    appId: '1:192519439615:ios:6642fb32e6f7549876b8ca',
    messagingSenderId: '192519439615',
    projectId: 'safestreet-6e08d',
    storageBucket: 'safestreet-6e08d.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbTjEHwE_gF985otrlxqx48KS8H5dT_N8',
    appId: '1:192519439615:ios:6642fb32e6f7549876b8ca',
    messagingSenderId: '192519439615',
    projectId: 'safestreet-6e08d',
    storageBucket: 'safestreet-6e08d.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYrDISVx7e5OmE2hlrDJQpwxDdbi-2rtk',
    appId: '1:192519439615:web:3bf1b5fa84f758ae76b8ca',
    messagingSenderId: '192519439615',
    projectId: 'safestreet-6e08d',
    authDomain: 'safestreet-6e08d.firebaseapp.com',
    storageBucket: 'safestreet-6e08d.firebasestorage.app',
  );
}
